---
title: Portfolio Jacek Rojek
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
title-bold: Jacek
title-normal: Rojek
email: j.rojek19@gmail.com
description: "Web Developer experienced in HTML5, CSS3 + SASS + Compass, JavaScript
  + jQuery + EM6. PHP, MySQL, CMS: Wordpress, static site generators: Jekyll.\nI'm
  writing a [blog about C# development](https://indiedevart.wordpress.com/)\nIn my
  free time I develop games using Unity3D with C#, combined with art in Photoshop/Gimp
  and animations in Blender.     "
baseurl: "/forty-jekyll-theme"
url: http://portfolio-jacekrojek.siteleaf.net/
author: Jacek Rojek
city: Leeds
country: United Kingdom
phone: '0 749 574 4394 '
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jemoji
tiles-source: posts
tiles-count: 6
500px_url: 
facebook_url: https://www.facebook.com/jacek.rojek.7
github_url: https://github.com/JacekRojek
gitlab_url: https://github.com/JacekRojek
googleplus_url: https://plus.google.com/u/1/110875553629766069606
instagram_url: https://www.instagram.com/jacekrojek/
linkedin_url: www.linkedin.com/in/jacek-rojek-b7a396105
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/JRojek93
markdown: kramdown
twitter:
  username: JRojek93
facebook:
  app_id: 
  publisher: 
  admins: 
logo: "/uploads/indiedevart1.png"
google_site_verification: 
